### ISSUE TITLE
Consolidate packages?

### ISSUE THREAD

**Issue by markcellus** [component/popover#11]
Hello, I have a similar popover component that I've been working on that is a [WebComponent](https://www.webcomponents.org/introduction). It offers a more modernized API for the component. Would you all mind collaborating on this effort and allowing me to add my code here?

**Comment by dy** [comment]
Please provide a PR and argumentation.
Ideally it should have same API, possibly upgraded to ES modules / web-components.

**Comment by markcellus** [comment]
Yeah that's what I'm proposing. But actually as I've thought about this, I'm going to just to create my own implementation. I didn't realize this package depends on a suite of your other components--my implementation would be without any dependencies and then there's a question of ownership since I'd be totally refactoring this entire lib haha. Thanks for considering though :+1:
